### ISSUE TITLE
Feature Request: Snapshot management

### ISSUE THREAD

**Issue by smatterchew** [ansible-collections/vmware.vmware_rest#351]
I would like to suggest a feature for the `vmware.vmware_rest` collection: Snapshot management.

The `community.vmware` collection has `vmware_guest_snapshot` that I was using to delete snapshots from a VM before converting it to a template.  I can't see how to do the same thing with the REST based collection.  I'm using v2.2.0, [documented here](https://docs.ansible.com/ansible/latest/collections/vmware/vmware_rest/index.html), and can find nothing related to snapshots.

Thank you.

**Comment by goneri** [comment]
Hi @smatterchew, the vmware_rest modules are built on top of the vSphere REST API. At this stage (vSphere 7.0.3), VMware doesn't provide yet any mechanism to manage the guest snapshots.

**Comment by smatterchew** [comment]
Thanks @goneri.  Interesting thread.  Looks like vmware has no intention to implement.

**Comment by mariolenz** [comment]
@CorruptBandit I don't think we should implement the same functionality in several of the VMware collections. There are _very_ few people working on them. It's better to join our forces and implement what's needed, but only once and not several times. At the end of the day, someone has to maintain this. That's why I've deprecated vmware_guest_snapshot in community.vmware (ansible-collections/community.vmware#2467).

As you say vmware.vmware has a module to manage snapshots. If it allows you to do what you need to do, I don't think it's important if it uses REST or SOAP. If you're missing some functionality, you should open an issue in vmware.vmware and describe what you need. If not, why do you care if the module uses the REST or SOAP API?

cc @mikemorency
